export { GlobalStyles } from './GlobalStyles';
export { Header } from './Header';
export { Navigation } from './Navigation';
export { WallpaperCard } from './WallpaperCard';
export { WallpaperGrid } from './WallpaperGrid';
export { SearchModal } from './SearchModal';
export { UploadModal } from './UploadModal';
export { UserProfile } from './UserProfile';
export { WallpaperDetail } from './WallpaperDetail';
